// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipIt.Infrastructure.Database;

#nullable disable

namespace ShipIt.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ShipItDbContext))]
    [Migration("20260707190445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ShipIt.Domain.Orders.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("CargoWeight")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("cargo_weight");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_number");

                    b.Property<DateOnly>("PickupDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("pickup_date");

                    b.Property<string>("RecipientCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_city");

                    b.Property<string>("SenderCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_city");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_orders_order_number");

                    b.ToTable("delivery_orders", (string)null);
                });

            modelBuilder.Entity("ShipIt.Domain.Orders.DeliveryOrder", b =>
                {
                    b.OwnsOne("ShipIt.Domain.Orders.ValueObjects.Address", "RecipientAddress", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOrderId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Apartment")
                                .HasColumnType("INTEGER")
                                .HasColumnName("recipient_apartment");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("recipient_house");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("recipient_street");

                            b1.HasKey("DeliveryOrderId");

                            b1.ToTable("delivery_orders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOrderId");
                        });

                    b.OwnsOne("ShipIt.Domain.Orders.ValueObjects.Address", "SenderAddress", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOrderId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Apartment")
                                .HasColumnType("INTEGER")
                                .HasColumnName("sender_apartment");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("sender_house");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("sender_street");

                            b1.HasKey("DeliveryOrderId");

                            b1.ToTable("delivery_orders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOrderId");
                        });

                    b.Navigation("RecipientAddress")
                        .IsRequired();

                    b.Navigation("SenderAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
